server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://bd-reservas-main:5432/reservas_db
    username: admin
    password: tu_password_seguro_produccion
  jpa:
    hibernate:
      ddl-auto: validate 
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect