server:
  port: 9002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/reservas_db
    username: admin
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true 